/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TUGAS1;

/**
 *
 * @author ASUS
 */
public class Output extends javax.swing.JFrame {
    String nama, nim, kelas;
    /**
     * Creates new form Output
     */

    public Output(String nama, String nim, String kelas) {
        initComponents();
        this.nama = nama;
        Lbnama.setText("Nama:" + this.nama);
        this.nim = nim;
        Lbnim.setText("NIM :" + this.nim);
        this.kelas = kelas;
        Lbkelas.setText("Kelas :" + this.kelas);
    }

    private Output() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lboutput = new javax.swing.JLabel();
        Lbnama = new javax.swing.JLabel();
        Lbnim = new javax.swing.JLabel();
        Lbkelas = new javax.swing.JLabel();
        Btnkembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lboutput.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Lboutput.setText("Output");

        Lbnama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lbnama.setText("Nama       :");

        Lbnim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lbnim.setText("NIM         :");

        Lbkelas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lbkelas.setText("Kelas        :");

        Btnkembali.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Btnkembali.setText("Kembali");
        Btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnkembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(Lboutput))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbnim)
                            .addComponent(Lbnama)
                            .addComponent(Lbkelas))))
                .addContainerGap(272, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Btnkembali)
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Lboutput)
                .addGap(24, 24, 24)
                .addComponent(Lbnama)
                .addGap(18, 18, 18)
                .addComponent(Lbnim)
                .addGap(18, 18, 18)
                .addComponent(Lbkelas)
                .addGap(28, 28, 28)
                .addComponent(Btnkembali)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnkembaliActionPerformed
        // TODO add your handling code here:
        Menu mainMenu = new Menu();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnkembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Output().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnkembali;
    private javax.swing.JLabel Lbkelas;
    private javax.swing.JLabel Lbnama;
    private javax.swing.JLabel Lbnim;
    private javax.swing.JLabel Lboutput;
    // End of variables declaration//GEN-END:variables
}
